export { registerWindowHandlers } from './window.ipc'
export { registerSystemHandlers } from './system.ipc'
export { registerLoggerHandlers } from './logger.ipc'
export { registerConfigHandlers } from './config.ipc'
export { registerWebViewHandlers } from './webview.ipc'
export { registerFolderHandlers } from './folder.ipc'
export { registerNovelHandlers } from './novel.ipc'
