nodeLinker: hoisted
overrides:
  '@electron/get': ^3.1.0
  stack-trace: 0.0.3
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  protobufjs: true
  sharp: true
