import type { Component } from "vue";
import {
  CheckCircleFilled,
  WbSunnyFilled,
  TipsAndUpdatesFilled,
  PushPinFilled,
  ForumFilled,
  ManageSearchFilled,
  InsightsFilled,
  EditNoteFilled,
  CalendarMonthFilled,
  ExtensionFilled,
  EditFilled,
  AutoStoriesFilled,
  LightbulbFilled,
  SchoolFilled,
  LibraryBooksFilled,
  MenuBookFilled,
  ScienceFilled,
  BiotechFilled,
  DescriptionFilled,
  NotesFilled,
  TaskAltFilled,
  EventNoteFilled,
  StickyNote2Filled,
  SummarizeFilled,
  PsychologyFilled,
  AutoAwesomeFilled,
  RocketLaunchFilled,
  CodeFilled,
  StarFilled,
  FlagFilled,
  BookmarkFilled,
  FolderFilled,
  FactCheckFilled,
  AssignmentFilled,
  QuestionAnswerFilled,
  FormatListBulletedFilled,
  RuleFilled,
  BoltFilled,
  VerifiedFilled,
  AccountBalanceFilled,
  TextSnippetFilled,
  NoteAltFilled,
  EventFilled,
  DrawFilled,
  HistoryFilled,
  FavoriteFilled,
} from "@vicons/material";
import {
  DEFAULT_TEMPLATE_ICON,
  type TemplateIconName,
} from "@/shared/enums/template.enums";

/** 可选图标键列表（供图标选择器等使用），直接透传 shared 枚举 */
export { TEMPLATE_ICON_NAMES } from "@/shared/enums/template.enums";

/** 图标键 -> @vicons/material 图标组件 的注册表（内置与自定义模板共用） */
export const TEMPLATE_ICONS: Record<TemplateIconName, Component> = {
  check_circle: CheckCircleFilled,
  wb_sunny: WbSunnyFilled,
  tips_and_updates: TipsAndUpdatesFilled,
  push_pin: PushPinFilled,
  forum: ForumFilled,
  manage_search: ManageSearchFilled,
  insights: InsightsFilled,
  edit_note: EditNoteFilled,
  calendar_month: CalendarMonthFilled,
  extension: ExtensionFilled,
  edit: EditFilled,
  auto_stories: AutoStoriesFilled,
  lightbulb: LightbulbFilled,
  school: SchoolFilled,
  library_books: LibraryBooksFilled,
  menu_book: MenuBookFilled,
  science: ScienceFilled,
  biotech: BiotechFilled,
  description: DescriptionFilled,
  notes: NotesFilled,
  task_alt: TaskAltFilled,
  event_note: EventNoteFilled,
  sticky_note: StickyNote2Filled,
  summarize: SummarizeFilled,
  psychology: PsychologyFilled,
  auto_awesome: AutoAwesomeFilled,
  rocket_launch: RocketLaunchFilled,
  code: CodeFilled,
  star: StarFilled,
  flag: FlagFilled,
  bookmark: BookmarkFilled,
  folder: FolderFilled,
  fact_check: FactCheckFilled,
  assignment: AssignmentFilled,
  question_answer: QuestionAnswerFilled,
  format_list_bulleted: FormatListBulletedFilled,
  rule: RuleFilled,
  bolt: BoltFilled,
  verified: VerifiedFilled,
  account_balance: AccountBalanceFilled,
  text_snippet: TextSnippetFilled,
  note_alt: NoteAltFilled,
  event: EventFilled,
  draw: DrawFilled,
  history: HistoryFilled,
  favorite: FavoriteFilled,
};

/** 把图标键解析为图标组件；非法/缺失键回退到默认图标 */
export function resolveTemplateIcon(
  icon: string | undefined | null,
): Component {
  return (
    TEMPLATE_ICONS[icon as TemplateIconName] ??
    TEMPLATE_ICONS[DEFAULT_TEMPLATE_ICON]
  );
}
