export enum ErrorCode {
  // ============ 成功 ============
  SUCCESS = "ERROR.SUCCESS",
  // ============ 通用错误============
  COMMON_UNKNOWN = "ERROR.COMMON.UNKNOWN",
  COMMON_INVALID_PARAMETER = "ERROR.COMMON.INVALID_PARAMETER",
  COMMON_ACTION_ERROR = "ERROR.COMMON.ACTION_ERROR",
  // ============ 配置错误 ============
  CONFIG_GET_FAILED = "ERROR.CONFIG.GET_FAILED",
  CONFIG_UPDATE_FAILED = "ERROR.CONFIG.UPDATE_FAILED",
  CONFIG_RESET_FAILED = "ERROR.CONFIG.RESET_FAILED",
  CONFIG_KEY_PATH_INVALID = "ERROR.CONFIG.KEY_PATH_INVALID",
  // ============ Webview 错误 ============
  WEBVIEW_CREATE_FAILED = "ERROR.WEBVIEW.CREATE_FAILED",
  WEBVIEW_LOAD_FAILED = "ERROR.WEBVIEW.LOAD_FAILED",
  WEBVIEW_RELOAD_FAILED = "ERROR.WEBVIEW.RELOAD_FAILED",
  WEBVIEW_DESTROY_FAILED = "ERROR.WEBVIEW.DESTROY_FAILED",
  WEBVIEW_GO_BACK_FAILED = "ERROR.WEBVIEW.GO_BACK_FAILED",
  WEBVIEW_GO_FORWARD_FAILED = "ERROR.WEBVIEW.GO_FORWARD_FAILED",
  WEBVIEW_GET_NAVIGATION_STATE_FAILED = "ERROR.WEBVIEW.GET_NAVIGATION_STATE_FAILED",
  WEBVIEW_URL_EMPTY = "ERROR.WEBVIEW.URL_EMPTY",
  WEBVIEW_FUNCTION_NOT_AVAILABLE = "ERROR.WEBVIEW.FUNCTION_NOT_AVAILABLE",
  WEBVIEW_RESIZE_FAILED = "ERROR.WEBVIEW.RESIZE_FAILED",
  WEBVIEW_HIDE_FAILED = "ERROR.WEBVIEW.HIDE_FAILED",

  // ============ 日志错误 ===========
  JOURNAL_CREATE_FAILED = "ERROR.JOURNAL.CREATE_FAILED",
  JOURNAL_GET_FAILED = "ERROR.JOURNAL.GET_FAILED",
  JOURNAL_UPDATE_FAILED = "ERROR.JOURNAL.UPDATE_FAILED",
  JOURNAL_DELETE_FAILED = "ERROR.JOURNAL.DELETE_FAILED",
  JOURNAL_QUERY_FAILED = "ERROR.JOURNAL.QUERY_FAILED",
  JOURNAL_NOT_FOUND = "ERROR.JOURNAL.NOT_FOUND",
  JOURNAL_COUNT_FAILED = "ERROR.JOURNAL.COUNT_FAILED",

  // ============ 作品错误 ============
  PROJECT_NOT_FOUND = "ERROR.PROJECT.NOT_FOUND",
  PROJECT_GET_FAILED = "ERROR.PROJECT.GET_FAILED",
  PROJECT_LIST_FAILED = "ERROR.PROJECT.LIST_FAILED",
  PROJECT_CREATE_FAILED = "ERROR.PROJECT.CREATE_FAILED",
  PROJECT_UPDATE_FAILED = "ERROR.PROJECT.UPDATE_FAILED",
  PROJECT_DELETE_FAILED = "ERROR.PROJECT.DELETE_FAILED",

  // ============ 标签错误 ============
  TAG_CREATE_FAILED = "ERROR.TAG.CREATE_FAILED",
  TAG_GET_FAILED = "ERROR.TAG.GET_FAILED",
  TAG_UPDATE_FAILED = "ERROR.TAG.UPDATE_FAILED",
  TAG_DELETE_FAILED = "ERROR.TAG.DELETE_FAILED",
  TAG_QUERY_FAILED = "ERROR.TAG.QUERY_FAILED",
  TAG_NOT_FOUND = "ERROR.TAG.NOT_FOUND",

  // ============ 模板错误 ============
  TEMPLATE_GET_FAILED = "ERROR.TEMPLATE.GET_FAILED",
  TEMPLATE_SAVE_FAILED = "ERROR.TEMPLATE.SAVE_FAILED",
  TEMPLATE_DELETE_FAILED = "ERROR.TEMPLATE.DELETE_FAILED",

  // ============ 下载错误 ============
  DOWNLOAD_FAILED = "ERROR.DOWNLOAD.FAILED",
  DOWNLOAD_CANCELLED = "ERROR.DOWNLOAD.CANCELLED",
  DOWNLOAD_URL_INVALID = "ERROR.DOWNLOAD.URL_INVALID",
  DOWNLOAD_DIR_CREATE_FAILED = "ERROR.DOWNLOAD.DIR_CREATE_FAILED",
  DOWNLOAD_FILE_WRITE_FAILED = "ERROR.DOWNLOAD.FILE_WRITE_FAILED",
  DOWNLOAD_TASK_NOT_FOUND = "ERROR.DOWNLOAD.TASK_NOT_FOUND",

  // ============ 任务队列错误 ============
  TASK_ENQUEUE_FAILED = "ERROR.TASK.ENQUEUE_FAILED",
  TASK_GET_FAILED = "ERROR.TASK.GET_FAILED",
  TASK_GET_GROUP_FAILED = "ERROR.TASK.GET_GROUP_FAILED",
  TASK_CANCEL_FAILED = "ERROR.TASK.CANCEL_FAILED",
  TASK_PROGRESS_FAILED = "ERROR.TASK.PROGRESS_FAILED",

  // ============ 智能任务错误 ============
  SMART_TASK_START_FAILED = "ERROR.SMART_TASK.START_FAILED",
  SMART_TASK_CANCEL_FAILED = "ERROR.SMART_TASK.CANCEL_FAILED",
  SMART_TASK_PAUSE_FAILED = "ERROR.SMART_TASK.PAUSE_FAILED",
  SMART_TASK_RESUME_FAILED = "ERROR.SMART_TASK.RESUME_FAILED",
  SMART_TASK_STATUS_FAILED = "ERROR.SMART_TASK.STATUS_FAILED",
  SMART_TASK_HISTORY_FAILED = "ERROR.SMART_TASK.HISTORY_FAILED",

  // ============ 日志错误 ============
  LOG_CREATE_FAILED = "ERROR.LOG.CREATE_FAILED",

  // ============ 通知错误 ============
  NOTIFICATION_ADD_ERROR = "ERROR.NOTIFICATION.ADD_ERROR",
  // ============ 系统错误 ============
  SYSTEM_GET_INFO_FAILED = "ERROR.SYSTEM.GET_INFO_FAILED",
  SYSTEM_OPEN_DIALOG_ERROR = "ERROR.SYSTEM.OPEN_DIALOG_ERROR",
  SYSTEM_OPEN_EXTERNAL_ERROR = "ERROR.SYSTEM.OPEN_EXTERNAL_ERROR",

  // ============ 模型错误 ============
  MODEL_GET_CONFIG_FAILED = "ERROR.MODEL.GET_CONFIG_FAILED",
  MODEL_GET_VALUE_FAILED = "ERROR.MODEL.GET_VALUE_FAILED",
  MODEL_SET_VALUE_FAILED = "ERROR.MODEL.SET_VALUE_FAILED",
  MODEL_RESET_CONFIG_FAILED = "ERROR.MODEL.RESET_CONFIG_FAILED",
  MODEL_DOWNLOAD_FAILED = "ERROR.MODEL.DOWNLOAD_FAILED",
  MODEL_CHECK_EXIST_FAILED = "ERROR.MODEL.CHECK_EXIST_FAILED",
  MODEL_REDOWNLOAD_FAILED = "ERROR.MODEL.REDOWNLOAD_FAILED",
  MODEL_CANCEL_DOWNLOAD_FAILED = "ERROR.MODEL.CANCEL_DOWNLOAD_FAILED",

  // ============ 页面错误 ============
  PAGE_NOT_FOUND = "ERROR.PAGE.NOT_FOUND",
  PAGE_GET_FAILED = "ERROR.PAGE.GET_FAILED",
  PAGE_LIST_FAILED = "ERROR.PAGE.LIST_FAILED",
  PAGE_CREATE_FAILED = "ERROR.PAGE.CREATE_FAILED",
  PAGE_UPDATE_FAILED = "ERROR.PAGE.UPDATE_FAILED",
  PAGE_DELETE_FAILED = "ERROR.PAGE.DELETE_FAILED",
  PAGE_QUERY_FAILED = "ERROR.PAGE.QUERY_FAILED",
  PAGE_COUNT_FAILED = "ERROR.PAGE.COUNT_FAILED",

  // ============ 主题错误 ============
  TOPIC_NOT_FOUND = "ERROR.TOPIC.NOT_FOUND",
  TOPIC_GET_FAILED = "ERROR.TOPIC.GET_FAILED",
  TOPIC_LIST_FAILED = "ERROR.TOPIC.LIST_FAILED",
  TOPIC_CREATE_FAILED = "ERROR.TOPIC.CREATE_FAILED",
  TOPIC_UPDATE_FAILED = "ERROR.TOPIC.UPDATE_FAILED",
  TOPIC_DELETE_FAILED = "ERROR.TOPIC.DELETE_FAILED",

  // ============ 概念错误 ============
  CONCEPT_NOT_FOUND = "ERROR.CONCEPT.NOT_FOUND",
  CONCEPT_GET_FAILED = "ERROR.CONCEPT.GET_FAILED",
  CONCEPT_LIST_FAILED = "ERROR.CONCEPT.LIST_FAILED",
  CONCEPT_CREATE_FAILED = "ERROR.CONCEPT.CREATE_FAILED",
  CONCEPT_UPDATE_FAILED = "ERROR.CONCEPT.UPDATE_FAILED",
  CONCEPT_DELETE_FAILED = "ERROR.CONCEPT.DELETE_FAILED",

  // ============ 反思错误 ============
  REFLECTION_NOT_FOUND = "ERROR.REFLECTION.NOT_FOUND",
  REFLECTION_GET_FAILED = "ERROR.REFLECTION.GET_FAILED",
  REFLECTION_LIST_FAILED = "ERROR.REFLECTION.LIST_FAILED",

  // ============ 时间事件错误 ============
  TEMPORAL_EVENT_LIST_FAILED = "ERROR.TEMPORAL_EVENT.LIST_FAILED",

  // ============ AI 网关错误 ============
  AI_NO_AVAILABLE_PROVIDER = "ERROR.AI.NO_AVAILABLE_PROVIDER",
  AI_MODEL_NOT_FOUND = "ERROR.AI.MODEL_NOT_FOUND",
  AI_REQUEST_FAILED = "ERROR.AI.REQUEST_FAILED",
  AI_PROVIDER_DISABLED = "ERROR.AI.PROVIDER_DISABLED",
  AI_TIMEOUT = "ERROR.AI.TIMEOUT",
  AI_INVALID_RESPONSE = "ERROR.AI.INVALID_RESPONSE",
  AI_STREAM_ERROR = "ERROR.AI.STREAM_ERROR",

  // ============ 更新错误 ============
  UPDATE_CHECK_FAILED = "ERROR.UPDATE.CHECK_FAILED",
  UPDATE_DOWNLOAD_FAILED = "ERROR.UPDATE.DOWNLOAD_FAILED",
  UPDATE_INSTALL_FAILED = "ERROR.UPDATE.INSTALL_FAILED",
}

/**
 * 错误分类类型
 */
export type ErrorCategory =
  | "COMMON" // 通用错误
  | "CONFIG" // 配置错误
  | "WEBVIEW" // Webview 错误
  | "JOURNAL" // 日志错误
  | "MODEL" // 模型错误
  | "LOG" // 日志错误
  | "NOTIFICATION" // 通知错误
  | "AGENT" // 智能体错误
  | "SYSTEM" // 系统错误
  | "PAGE" // 页面错误
  | "TOPIC" // 主题错误
  | "CONCEPT" // 概念错误
  | "REFLECTION" // 反思错误
  | "TEMPORAL_EVENT" // 时间事件错误
  | "AI" // AI 网关错误
  | "UPDATE" // 更新错误
  | "TEMPLATE" // 模板错误
  | "UNKNOWN" // 未知分类
  | "SUCCESS"; // 成功分类

/**
 * 根据错误代码获取错误分类
 * @param errorCode - 错误代码
 * @returns 错误分类
 */
export function getErrorCategory(errorCode: ErrorCode): ErrorCategory {
  // 提取首个下划线前的字符串
  const category = errorCode.split("_")[0];

  // 根据分类字符串返回对应的错误分类
  switch (category) {
    case "COMMON":
      return "COMMON";
    case "CONFIG":
      return "CONFIG";
    case "WEBVIEW":
      return "WEBVIEW";
    case "JOURNAL":
      return "JOURNAL";
    case "LOG":
      return "LOG";
    case "MODEL":
      return "MODEL";
    case "NOTIFICATION":
      return "NOTIFICATION";
    case "SYSTEM":
      return "SYSTEM";
    case "PAGE":
      return "PAGE";
    case "TOPIC":
      return "TOPIC";
    case "CONCEPT":
      return "CONCEPT";
    case "REFLECTION":
      return "REFLECTION";
    case "TEMPORAL":
      return "TEMPORAL_EVENT";
    case "AI":
      return "AI";
    case "UPDATE":
      return "UPDATE";
    case "TEMPLATE":
      return "TEMPLATE";
    case "AGENT":
      return "AGENT";
    case "SUCCESS":
      return "SUCCESS";
    default:
      return "UNKNOWN";
  }
}

/**
 * 获取所有错误分类的映射关系
 * @returns 错误分类到错误代码数组的映射
 */
export function getErrorCategoryMap(): Record<ErrorCategory, ErrorCode[]> {
  const categoryMap: Record<ErrorCategory, ErrorCode[]> = {
    COMMON: [],
    CONFIG: [],
    WEBVIEW: [],
    JOURNAL: [],
    MODEL: [],
    LOG: [],
    NOTIFICATION: [],
    AGENT: [],
    SYSTEM: [],
    PAGE: [],
    TOPIC: [],
    CONCEPT: [],
    REFLECTION: [],
    TEMPORAL_EVENT: [],
    AI: [],
    UPDATE: [],
    TEMPLATE: [],
    UNKNOWN: [],
    SUCCESS: [],
  };

  // 遍历所有错误代码，按分类分组
  Object.values(ErrorCode).forEach((errorCode) => {
    const category = getErrorCategory(errorCode);
    categoryMap[category].push(errorCode);
  });

  return categoryMap;
}

/**
 * 获取指定分类的所有错误代码
 * @param category - 错误分类
 * @returns 该分类下的所有错误代码
 */
export function getErrorCodesByCategory(category: ErrorCategory): ErrorCode[] {
  const categoryMap = getErrorCategoryMap();
  return categoryMap[category] || [];
}

/**
 * 检查错误代码是否属于指定分类
 * @param errorCode - 错误代码
 * @param category - 错误分类
 * @returns 是否属于该分类
 */
export function isErrorCodeInCategory(
  errorCode: ErrorCode,
  category: ErrorCategory,
): boolean {
  return getErrorCategory(errorCode) === category;
}
